rescue

diff --git a/tasks/services.yml b/tasks/services.yml
--- a/tasks/services.yml
+++ b/tasks/services.yml
@@ -31,29 +31,36 @@
 # creates svc.sh
 - name: register={{ repo.name }},runner={{ runner_instance_name }}
   become: false
-  shell: |
-      cd {{ repo_install_dir }}
-      # issue a token for this repository to administrate runners
-      res=$(curl -L \
-        -X POST \
-        -H "Accept: application/vnd.github+json" \
-        -H "Authorization: Bearer {{ runners_token }}" \
-        -H "X-GitHub-Api-Version: 2022-11-28" \
-        https://api.github.com/repos/{{ runners_owner }}/{{ repo.name }}/actions/runners/registration-token
-      )
-      if [ 0 -ne $? ]; then
-        echo "failed to get registration token: ${res}"
-        exit 1
-      fi
-      token=$(echo ${res} | jq -r .token)
-      ./config.sh \
-        --unattended \
-        --labels '{{ runners_labels }}' \
-        --name '{{ runner_instance_name }}' \
-        --url https://github.com/{{ runners_owner }}/{{ repo.name }} \
-        --token ${token}
+  block:
+    - shell: |
+        cd {{ repo_install_dir }}
+        # issue a token for this repository to administrate runners
+        res=$(curl -L \
+          -X POST \
+          -H "Accept: application/vnd.github+json" \
+          -H "Authorization: Bearer {{ runners_token }}" \
+          -H "X-GitHub-Api-Version: 2022-11-28" \
+          https://api.github.com/repos/{{ runners_owner }}/{{ repo.name }}/actions/runners/registration-token
+        )
+        if [ 0 -ne $? ]; then
+          echo "failed to get registration token: ${res}"
+          exit 1
+        fi
+        token=$(echo ${res} | jq -r .token)
+        ./config.sh \
+          --unattended \
+          --labels '{{ runners_labels }}' \
+          --name '{{ runner_instance_name }}' \
+          --url https://github.com/{{ runners_owner }}/{{ repo.name }} \
+          --token ${token}
+        register: runner_registration
+  rescue:
+    - debug:
+      msg:
+        - '{{ runner_registration.stdout }}'
+        - '{{ runner_registration.stderr }}'
 
-# hack copy svc.sh to repo_install_dir
+  # hack copy svc.sh to repo_install_dir
 - name: mv svc.sh, runner={{ runner_instance_name }}
   become: true
   shell: |
