refactor(register.runner): log in case of error

diff --git a/tasks/services.yml b/tasks/services.yml
--- a/tasks/services.yml
+++ b/tasks/services.yml
@@ -33,14 +33,18 @@
   shell: |
       cd {{ repo_install_dir }}
       # issue a token for this repository to administrate runners
-      token=$(curl -L \
+      res=$(curl -L \
         -X POST \
         -H "Accept: application/vnd.github+json" \
         -H "Authorization: Bearer {{ runners_token }}" \
         -H "X-GitHub-Api-Version: 2022-11-28" \
-        https://api.github.com/repos/{{ runners_owner }}/{{ repo.name }}/actions/runners/registration-token \
-        | jq -r .token
+        https://api.github.com/repos/{{ runners_owner }}/{{ repo.name }}/actions/runners/registration-token
       )
+      if [ 0 -ne $? ]; then
+        echo "failed to get registration token: ${res}"
+        exit 1
+      fi
+      token=$(echo ${res} | jq -r .token)
       ./config.sh \
         --unattended \
         --labels '{{ runners_labels }}' \
